name: Docker Build

on:
  push:
    branches: '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Docker
        uses: docker/setup-buildx-action@v3

      - name: Build da imagem Docker
        run: docker build -t meu-site .

      - name: Ver imagem criadas
        run: docker images
